global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: "/health"
    static_configs:
      - targets: ["fastapi:8000"]

  - job_name: "nestjs"
    metrics_path: "/health"
    static_configs:
      - targets: ["nestjs:3001"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  - job_name: "rabbitmq"
    metrics_path: "/api/overview"
    static_configs:
      - targets: ["rabbitmq:15672"]
